### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by smackintosh** [marquete/kibo#13]
We would very much like to use Kibo within our project, but we are unable to because there is no copyright message anywhere in either the js source file or the readme. 

Our open source police are quite stringent! 

Please could the author add a copyright. 

Regards, 
Stuart

**Comment by marquete** [comment]
Hi, Stuart.

Up until now, I had assumed that releasing Kibo under an MIT license and making it publicly available on Github would be enough to consider it "no-strings-attached public domain", i.e. do whatever you want with it, I just don't care. It has just been pointed out to me that the Berne Convention dictates that I own the exclusive copyright to software I've written unless otherwise specified. The thing is, I don't really speak Legalese. Do you think you could help me with this? Thanks!

**Comment by smackintosh** [comment]
Yes I suspect that for most people the fact that it is MIT licensed would be good enough, but actually this does not make it "public domain" in the true sense. Copyright is more about your rights as the author not to be copied without consent and is something the legals will look to establish who the author is claimed as and therefore who has the authority to decide the licensing and other terms. The Berne Union is the worldwide agreement to enforce copyrights of works authored in other countries, although countries also have their own rules and not all countries belong to the union. For our purposes, would you be able to add a copyright message somewhere, this should look like "Copyright @ 2013 Full name. All rights reserved."

**Comment by marquete** [comment]
Hi again!

I left out the "All rights reserved" part since it's been obsolete since 2000 and has no legal significance anymore, but I hope this will be enough for your needs: https://github.com/marquete/kibo/commit/cf608865b6cca111966a5c03e85d72add366373d

Thanks for your help!
